
export const ALLIANCE_DARES: string[] = [
  "Try to speak in a baby voice for the next 3 rounds.",
  "Swap shirts with the person on your right for 10 minutes.",
  "Call a random contact and sing them “Happy Birthday.”",
  "Wear socks on your hands until your next turn.",
  "Let the group send any emoji to the last person you texted.",
  "Eat a spoonful of a weird food combo chosen by the group.",
  "Dance like a chicken in slow motion for 1 minute.",
  "Let someone write something on your forehead with a marker.",
  "Pretend to be a waiter and take orders from everyone for 2 minutes.",
  "Put an ice cube in your shirt until it melts.",
  "Act like you’re in a shampoo commercial for 30 seconds.",
  "Let two people switch your hairstyle.",
  "Speak only in questions until your next turn.",
  "Make up a romantic story about the person to your left.",
  "Let someone draw a mustache on your face.",
  "Do your best impression of any player in the group.",
  "Wear a blindfold and let someone feed you something.",
  "Read aloud the last 5 messages you sent.",
  "Hold a water bottle on your head for 1 minute without dropping.",
  "Try to lick your elbow while the group watches.",
  "Sing like you’re in an opera for 1 minute.",
  "Speak in a fake accent chosen by the group for 3 turns.",
  "Pretend you’re a cat and rub against everyone’s legs.",
  "Wear someone else’s shoes until your next turn.",
  "Try to make everyone laugh without speaking.",
  "Take a selfie making the ugliest face possible and post it on your story.",
  "Pretend to propose to the person across from you.",
  "Do a runway walk while the group rates you.",
  "Make animal noises for each person in the group.",
  "Stand in the corner facing the wall for 2 minutes.",
  "Balance an object on your head until your turn comes again.",
  "Let someone pick a filter and take your photo.",
  "Act like a movie villain for 1 minute.",
  "Pretend to faint dramatically in the middle of the group.",
  "Walk around like a zombie until your next turn.",
  "Let someone tickle you for 15 seconds.",
  "Hug the person on your left for 30 seconds straight.",
  "Attempt a cartwheel (or your version of it).",
  "Compliment everyone in the group in the weirdest way possible.",
  "Hold hands with someone until your next turn.",
  "Do 10 pushups while making animal noises.",
  "Let the group style your hair using random items.",
  "Pretend to cry loudly for 30 seconds.",
  "Sit on the floor and act like a toddler throwing a tantrum.",
  "Let someone make you a weird “hat” out of whatever’s around.",
  "Try to recite the alphabet backwards.",
  "Wear sunglasses indoors and act like a celebrity.",
  "Let the person on your right control your phone for 1 minute.",
  "Speak only in song lyrics for the next 2 rounds.",
  "End your turn by dramatically walking out of the room, then re-enter."
];
