
export const DARES: string[] = [
  "Send your crush 'I think my fridge likes you' and don’t explain.",
  "Do 10 push-ups… in slow motion… while making karate noises.",
  "Set your phone language to Chinese for 1 hour.",
  "Try to lick your elbow for 30 seconds straight.",
  "Record a 5-second video of you singing 'Happy Birthday' to your water bottle.",
  "Text your mom: 'I accidentally adopted a goat.'",
  "Hold a plank while reciting the alphabet backwards.",
  "Call a friend and tell them you can’t find your invisible socks.",
  "Balance a book on your head for 2 minutes without it falling.",
  "Pretend to interview your shoe about its day.",
  "Change your Instagram bio to 'Professional Potato Inspector' for 24 hours.",
  "Do 15 squats while shouting random fruit names.",
  "Send your best friend a photo of your ear and nothing else.",
  "Walk backwards around the room for 2 minutes.",
  "Call a random contact and meow until they hang up.",
  "Type a WhatsApp message using only your nose.",
  "Do 20 jumping jacks while singing your favorite song off-key.",
  "Post a selfie with your hair messed up captioned 'CEO of Chaos'.",
  "Hold your phone above your head and take a selfie without looking.",
  "Eat something without using your hands.",
  "Pretend your phone is a hot potato for 30 seconds.",
  "Reply to the last 3 texts you got with only emojis.",
  "Do a slow-motion run across the room like in a movie.",
  "Balance on one foot and text your friend 'HELP' without falling.",
  "Wear socks on your hands for the next 15 minutes.",
  "Make a 5-second motivational speech to your toothbrush.",
  "Call someone and sing 'Twinkle Twinkle Little Star' in a scary voice.",
  "Try to unlock your phone with your toes.",
  "Hold your breath and send a text before exhaling.",
  "Post 'I am inevitable' on your WhatsApp status and don’t reply to anyone.",
  "Do 10 sit-ups while holding your phone above your face.",
  "Try to whistle with water in your mouth.",
  "Send a friend the first picture in your gallery without context.",
  "Pretend your charger cable is a snake and you’re scared of it.",
  "Walk like a crab for 1 minute.",
  "Record yourself saying the alphabet backwards.",
  "Pretend to be a phone salesman and try to sell your phone to someone.",
  "Do 5 push-ups every time you hear a notification sound for the next 10 minutes.",
  "Type an entire sentence with your non-dominant hand and send it to a friend.",
  "Wear sunglasses indoors for the next hour.",
  "Balance your phone on your forehead for 30 seconds.",
  "Do 15 jumping jacks while holding your phone.",
  "Pretend your phone is a baby and rock it to sleep for 1 minute.",
  "Send a voice note of you pretending to be a robot.",
  "Take a selfie making the ugliest face possible and send it to your crush.",
  "Say 'I love you' to your phone 5 times.",
  "Record a video of you dancing without music.",
  "Do a wall sit while typing a message.",
  "Pretend your phone is too heavy to lift and struggle with it.",
  "Send a voice note of you singing the ABC song to your crush",
  "Hold a plank until you can recite the alphabet backward",
  "Call a random number and say 'I found the banana'",
  "Do 10 push-ups while pretending you're on the moon",
  "Send your mom a text saying 'I just adopted 6 pigeons'",
  "Type 'I am Batman' in every chat you have on WhatsApp",
  "Stand up and scream 'Pineapple belongs on pizza' in public",
  "Balance a spoon on your nose for 1 minute",
  "Pretend to do a photoshoot with your phone’s flashlight on",
  "Change your phone wallpaper to a picture of a potato",
  "Spin in a chair 15 times and then try to type your name",
  "Send your friend a selfie with toothpaste on your face",
  "Hold your breath and see if you can take a selfie",
  "Set your phone ringtone to a goat sound for the next day",
  "Do 20 squats while holding your phone on your head",
  "Text 'Help, I’m stuck in the fridge' to a random contact",
  "Pretend your phone is a sandwich and take a bite",
  "Write a breakup text to your phone service provider",
  "Call a pizza place and ask if they sell tacos",
  "Do a push-up for every app you have installed",
  "Send your friend a picture of your elbow",
  "Pretend your phone is a baby and rock it to sleep",
  "Change your contact name to 'Lord of Memes' for 24 hours",
  "Send a message to someone using only emojis",
  "Call your best friend and say 'meow' until they hang up",
  "Try to unlock your phone with your nose",
  "Put your phone in your sock for 5 minutes",
  "Text someone 'I am watching you' and nothing else",
  "Send the oldest selfie on your phone to a group chat",
  "Squat 10 times every time you get a notification for 1 hour",
  "Record a video pretending to be a phone salesman",
  "Ask Siri/Google to tell you a joke and repeat it to a friend",
  "Post 'I love broccoli' on your story",
  "Take a selfie with the weirdest face you can make",
  "Send your crush a meme without any text",
  "Call someone and ask if they sell spaghetti milkshakes",
  "Text 'It has begun' to the last person you texted",
  "Pretend your phone is too hot to touch for 2 minutes",
  "Send your friend a video of you whispering 'Shrek is love'",
  "Run 10 laps around your chair",
  "Screenshot your home screen and send it to a friend",
  "Do a 30-second dance with your phone in your hand",
  "Make a TikTok pretending your phone is your pet",
  "Send a 'Happy Birthday' text to someone whose birthday it isn’t",
  "Do 15 push-ups for every unread notification you have",
  "Change your bio to 'Professional Chicken Hugger'",
  "Pretend your phone is a soap bar and wash it (carefully)",
  "Say 'banana' 20 times into your phone recorder",
  "Send your dad a picture of your foot",
  "Call a random contact and ask 'Do you believe in aliens?'",
  "Post a selfie with no explanation",
  "Send your crush a heart emoji every minute for 10 minutes",
  "Do a plank while reading your last 5 messages out loud",
  "Take a mirror selfie with your tongue out",
  "Pretend your phone is a magic wand and cast spells",
  "Record yourself doing the chicken dance",
  "Do a headstand while holding your phone",
  "Send your friend the weirdest GIF you can find",
  "Call a contact and just breathe heavily",
  "Change your phone name to 'The Potato' for a day",
  "Say 'I am Groot' to everyone who messages you for 1 hour",
  "Post a picture of your ceiling on Instagram",
  "Do 20 push-ups while saying 'I love my phone'",
  "Send a selfie to a random number",
  "Pretend you are a news reporter and read your last text",
  "Put your phone in your shoe for 5 minutes",
  "Send your crush a potato emoji and nothing else",
  "Change your alarm to a chicken sound",
  "Do 15 squats every time you get a notification for 30 min",
  "Post 'Anyone selling a submarine?' on Facebook",
  "Call your best friend and ask 'How’s the weather in space?'",
  "Make a TikTok acting like you’re arguing with your phone",
  "Screenshot your lock screen and post it",
  "Say 'pineapple' in every sentence for 5 minutes",
  "Do 20 jumping jacks holding your phone",
  "Text 'I am outside your window' to a random contact",
  "Balance your phone on your pinky finger for 1 minute",
  "Post a random fact about ducks on your story",
  "Call someone and whisper 'The chicken has escaped'",
  "Send a voice note of you making cat sounds",
  "Pretend your phone is a mirror and fix your hair",
  "Change your profile pic to a spoon for 24 hours",
  "Send your boss a thumbs-up emoji at midnight",
  "Do 10 sit-ups while holding your phone on your chest",
  "Send the last picture in your gallery to your crush",
  "Say 'I am the Eggman' to the next person you call",
  "Make your phone background a close-up of your eye",
  "Post 'I lost my pet rock' online",
  "Text someone 'I’m eating soap' and see what they say",
  "Pretend to be Siri and answer your friend’s question",
  "Take a slow-motion video of you blinking",
  "Do 15 burpees with your phone in your pocket",
  "Send your sibling a random movie quote",
  "Say 'pickle' 30 times into your voice recorder",
  "Post a picture of a random object in your house",
  "Call your friend and only speak in song lyrics",
  "Pretend your phone is a puppy and pet it",
  "Send your crush a meme about onions",
  "Change your ringtone to a baby crying",
  "Record a video of you saying 'I am invincible'",
  "Do 10 push-ups while saying 'I love cheese'",
  "Send your mom a text saying 'I ate the TV remote'",
  "Post 'Looking for a horse trainer' on your social media",
  "Call someone and ask if they want to buy a cloud",
  "Send a random animal picture to 5 people",
  "Pretend you are in a shampoo commercial and record it",
  "Change your lock screen to a meme",
  "Post 'Bananas are taking over the world' on Twitter",
  "Do a cartwheel holding your phone (carefully)",
  "Send a random number a photo of your fridge",
  "Say 'meow' every time you get a notification for 1 hour",
  "Change your phone language to Spanish for 1 hour",
  "Call someone and ask 'Have you seen my pet goldfish?'",
  "Post a picture of your socks on Instagram",
  "Record a video pretending to be a YouTuber",
  "Do 15 jumping jacks every time you get a message for 30 min",
  "Send your crush a selfie with no caption",
  "Say 'banana pancakes' 10 times into your recorder",
  "Post 'Anyone selling invisible ink?' on Facebook",
  "Pretend to sneeze into your phone",
  "Call someone and ask if they know the Muffin Man",
  "Send your sibling a potato emoji every hour",
  "Make a TikTok pretending your phone is haunted",
  "Post a random screenshot from your gallery",
  "Do 10 squats while holding your phone on your head",
  "Call a contact and say 'The eagle has landed'",
  "Text your crush 'I can smell you'",
  "Send a random meme to your mom",
  "Post 'Is water wet?' online",
  "Do 15 sit-ups every time you get a message for 20 min",
  "Record yourself singing 'Happy Birthday' to your phone",
  "Pretend you are lost and ask your phone for directions",
  "Send your dad a selfie of you crying (fake tears)",
  "Post 'Looking for a pet dinosaur' on social media",
  "Call someone and ask 'Have you seen my left sock?'",
  "Take a selfie with your tongue touching your nose",
  "Change your bio to 'Full-time potato, part-time human'",
  "Send your best friend a message in Morse code",
  "Post 'Free hugs for aliens' on Twitter",
  "Record a video of you winking repeatedly",
  "Do 20 squats holding your phone",
  "Send your mom a picture of your feet",
  "Call your crush and say 'moo' until they hang up",
  "Pretend your phone is a burger and eat it",
  "Change your ringtone to a scream sound",
  "Post a photo of the sky with no caption",
  "Text 'The prophecy is true' to a random contact",
  "Record yourself doing a victory dance",
  "Do 15 jumping jacks with your phone on your head",
  "Send your sibling a video of you making weird noises",
  "Post 'Looking for a unicorn breeder' online",
  "Call someone and ask if they like bread",
  "Send your crush a photo of a random kitchen utensil",
  "Change your phone wallpaper to a selfie of you frowning",
  "Pretend to be an ASMR artist and record 1 minute of sounds",
  "Post a random number on your social media",
  "Do 10 burpees while holding your phone",
  "Send your friend a text saying 'The cake is a lie'",
  "Record yourself clapping for 30 seconds",
  "Call your mom and say 'I adopted a penguin'",
  "Post a blurry selfie online",
  "Send a random contact the word 'Pickle'",
  "Pretend your phone is a walkie-talkie for 1 hour",
  "Do 15 sit-ups while singing",
  "Send your crush a random GIF",
  "Post 'Looking for a potato costume' on Facebook",
  "Call someone and ask if they know where my spaceship is",
  "Take a selfie wearing sunglasses indoors",
  "Record yourself saying 'Banana power!'",
  "Send your sibling a picture of a chair",
  "Change your profile picture to a sock",
  "Pretend your phone is a baby and sing a lullaby",
  "Post 'Do ants have feelings?' on social media",
  "Call a random contact and sing 'Happy Birthday' even if it's not their birthday",
  "Text your crush a selfie of you making your ugliest face",
  "Speak in a British accent for the next 10 minutes",
  "Do 20 push-ups while someone records you",
  "Post 'I love pineapple on pizza' on your social media",
  "Pretend to be an Instagram influencer for 5 minutes",
  "Do 15 squats while holding your phone over your head",
  "Change your phone's language to Chinese for an hour",
  "Take a mirror selfie while flexing your nonexistent abs",
  "Send a 'good morning' text to the last person you argued with",
  "Balance a book on your head for 2 minutes",
  "Do 10 burpees while holding your phone",
  "Set your phone wallpaper to a photo of your nostrils",
  "Text a random contact 'Guess what? Chicken butt!'",
  "Do a TikTok dance in public",
  "Hold a plank position for 60 seconds while humming",
  "Send a voice note singing a lullaby to a friend",
  "Change your Instagram bio to 'Professional Potato'",
  "Stand up and do jumping jacks for 1 minute",
  "Send your mom a message saying 'I joined the circus'",
  "Record yourself doing your worst dance move",
  "Pretend to be a motivational speaker for 1 minute",
  "Put your phone upside down and type a sentence",
  "Do 30 calf raises while talking on the phone",
  "Post 'Anyone want free pizza?' and don't explain",
  "Make a 15-second video pretending to be a news anchor",
  "Do 10 push-ups while smiling at the camera",
  "Call a random contact and talk in song lyrics only",
  "Put on socks on your hands for 5 minutes",
  "Set your alarm for 3:00 AM and label it 'Dance Party'",
  "Send a random emoji to 5 people in your contacts",
  "Do a yoga pose and send the pic to a group chat",
  "Text 'I need bail money' to a random friend",
  "Hold your phone with your toes and take a picture",
  "Do wall sits for 60 seconds",
  "Pretend your phone is a baby and sing it a lullaby",
  "Send a selfie with toothpaste on your face",
  "Change your ringtone to something embarrassing",
  "Type with your elbows for 1 minute",
  "Send a message to someone with only emojis",
  "Do a slow-motion run video in your room",
  "Put your phone in your pocket and record yourself jumping",
  "Call someone and ask if they can hear you from space",
  "Spin around 10 times and try to text a sentence",
  "Post 'Just finished my underwater basket weaving class'",
  "Do 15 lunges while holding your phone like a trophy",
  "Make your lock screen a photo of a potato",
  "Send 'I see you' to the wrong number",
  "Speak in slow motion for the next 2 minutes",
  "Change your phone contact name for yourself to 'The Legend'",
  "Do 25 jumping jacks while singing",
  "Record yourself pretending to be a workout trainer",
  "Balance a spoon on your nose for 30 seconds",
  "Call someone and pretend to be lost in your own house",
  "Do push-ups but clap between each one",
  "Change your profile picture to a baby photo",
  "Send a friend a list of random animal noises",
  "Do a squat every time you get a message for 10 minutes",
  "Type a sentence without using your thumbs",
  "Post 'Bananas are my spirit animal'",
  "Do 20 sit-ups while holding your phone",
  "Call someone and tell them a joke with a serious voice",
  "Send a selfie pretending you’re crying over spilled milk",
  "Make a 'duck face' selfie and send it to your crush",
  "Hop on one leg for 30 seconds while scrolling",
  "Do a 1-minute plank with your phone on your back",
  "Pretend your phone is super heavy and struggle to hold it",
  "Send the alphabet backwards to a random contact",
  "Post 'Looking for someone to adopt my pet rock'",
  "Pretend your phone is a walkie-talkie for 5 minutes",
  "Send your location to a friend and say 'Help, I’m lost'",
  "Set a reminder for 5 minutes later saying 'Dance Now!'",
  "Do 15 push-ups with one hand on your phone",
  "Post a meme with no caption",
  "Change your group chat name to 'The Avengers'",
  "Send a message to someone saying 'I smell cheese'",
  "Put your phone on your head and walk across the room",
  "Do air guitar with your phone as the guitar",
  "Pretend to be on a cooking show for 1 minute",
  "Take a blurry selfie and post it",
  "Send a GIF of a llama to 3 people",
  "Change your alarm sound to a baby crying",
  "Hold your phone like it's a priceless artifact",
  "Text 'I’m in a parallel universe' to someone",
  "Do 10 frog jumps while recording",
  "Send a message using only one vowel letter",
  "Pretend you’re in slow motion for 20 seconds",
  "Post 'I just ate an entire jar of pickles'",
  "Call someone and whisper the whole conversation",
  "Take a selfie pretending you’re shocked at your phone",
  "Send your lock screen screenshot to someone",
  "Record a fake 'phone unboxing' video",
  "Do shadow boxing for 1 minute",
  "Text 'I’m watching you' to a random number",
  "Post 'I can talk to pigeons' and don’t explain",
  "Do the worm dance move",
  "Pretend your phone is a sandwich and eat it",
  "Send a selfie with a weird filter",
  "Record yourself running in place for 30 seconds",
  "Call someone and act like you’re ordering pizza from them",
  "Post 'I lost my left sock, please return it if found'",
  "Balance your phone on your foot for 15 seconds",
  "Text only with caps lock for 10 minutes",
  "Send a voice note pretending you’re a radio host",
  "Do 5 cartwheels in a row",
  "Pretend you’re a robot for 1 minute",
  "Call someone and say 'Meow' until they hang up",
  "Take a selfie with something random on your head",
  "Post 'I can’t stop thinking about potatoes'",
  "Send 5 people the same random photo",
  "Hold your phone in your mouth and take a selfie",
  "Do 10 jumping squats",
  "Record yourself pretending to be stuck in traffic",
  "Send 'I just sneezed 17 times in a row' to someone",
  "Change your phone’s brightness to minimum for an hour",
  "Do a crab walk for 30 seconds",
  "Pretend your phone is a mirror and admire yourself",
  "Post 'Looking for a unicorn trainer'",
  "Call a friend and speak in rhyme only",
  "Balance on one leg while texting",
  "Send a 'good night' text at noon",
  "Record a fake advertisement for your phone",
  "Do sit-ups while holding your phone above your head",
  "Send the same emoji 20 times to someone",
  "Pretend to be an ASMR YouTuber for 1 minute",
];
