
export const DARES_SERIOUS: string[] = [
  "Hold a wall-sit for 5 minutes straight — no breaks.",
  "100 push-ups in one go — failure means you restart.",
  "Do a 3-minute plank while someone pours cold water on you.",
  "50 burpees with no stopping.",
  "Keep your hands in ice water for 3 minutes.",
  "Jump in place for 10 minutes.",
  "Hold a squat position with arms out for 7 minutes.",
  "Do 300 jumping jacks non-stop.",
  "Bear crawl across the room and back — 5 rounds.",
  "Hold a heavy object at arm’s length for 2 minutes.",
  "20 jump squats, then immediately 20 push-ups, repeat 3x.",
  "Carry someone on your back for 2 minutes.",
  "Crawl under a table 20 times.",
  "Hold your breath underwater as long as possible (safely).",
  "Eat one raw chili and don’t drink water for 2 minutes.",
  "5 minutes of shadowboxing at max speed.",
  "Push-up position with one arm for 30 seconds each side.",
  "100 mountain climbers non-stop.",
  "Plank with one leg raised for 1 minute per side.",
  "Lie on your back and hold your legs at 45° for 2 minutes.",
  "Do 50 burpees without stopping.",
  "100 push-ups in one go — no breaks longer than 10 seconds.",
  "Run in place with high knees for 3 minutes straight.",
  "Do a 10-minute plank hold (yes, full 10 — restart if you drop).",
  "Do 200 squats in one go.",
  "Hold a squat position while holding something heavy above your head for 3 minutes.",
  "Jump squat 50 times without stopping.",
  "Crawl across the entire room using only elbows and toes.",
  "Do a 1-minute L-sit hold on the floor.",
  "100 mountain climbers — no pause.",
  "Bear crawl around the house twice.",
  "Stand on one foot for 5 minutes — restart if you drop.",
  "Sprint in place for 1 minute at full speed.",
  "Hold push-up position for 5 minutes.",
  "20 one-legged squats on each leg.",
  "Crab walk across the room and back — 5 rounds.",
  "100 jumping lunges.",
  "Plank with one leg raised for 2 minutes each side.",
  "Carry something heavy (bucket of water, bag of rice) above your head for 5 minutes.",
  "Jump rope for 10 minutes straight (no tripping allowed).",
  "Side plank 2 minutes each side.",
  "50 tricep dips on a chair.",
  "Frog jumps across the room and back — 5 rounds.",
  "Push-up hold halfway down for 2 minutes.",
  "Do 30 burpees, but every time you land, do a push-up before jumping again.",
  "Sit against the wall with feet off the ground for 2 minutes.",
  "50 shoulder taps from plank position.",
  "Sprint up and down stairs 10 times without break.",
  "Run up and down the stairs 10 times without stopping.",
  "Hold a plank until your body starts shaking.",
  "Do 25 push-ups with no breaks.",
  "Balance in a squat position with hands over head for 3 minutes.",
  "Jump as high as possible 30 times in a row.",
  "Stand on one leg for 4 minutes without touching anything.",
  "Bear crawl across the room 10 times.",
  "Do 20 mountain climbers — slow and controlled.",
  "Hold the “chair” yoga pose against a wall for 2 minutes.",
  "Do 10 push-ups, but lower yourself as slowly as possible.",
  "Hold your arms straight out at shoulder level for 3 minutes without lowering them.",
  "Run in place as fast as you can for 1 minute.",
  "Crab walk across the room and back 5 times.",
  "Do 10 lunges per leg — slow and deep.",
  "Jump rope for 3 minutes without stopping (if no rope, jump in place).",
  "Hold a high plank for 2 minutes, then immediately 20 push-ups.",
  "Squat down and hold for 3 minutes while clapping every 5 seconds.",
  "Do 10 donkey kicks per leg.",
  "Lay flat, then get up without using your hands — 5 times.",
  "Hold the downward dog yoga pose for 2 minutes.",
  "Sit in a wall squat while holding something heavy for 2 minutes.",
  "Do 15 squat jumps without rest.",
  "Walk like a duck for 20 steps.",
  "Hold the push-up position halfway down for 30 seconds.",
  "Do 10 high jumps, touching the ceiling or highest point you can.",
  "Lie on your back and keep your legs 6 inches above the ground for 1 minute.",
  "Do 20 calf raises on one leg.",
  "Stand up and sit down from the floor without using your hands 5 times.",
  "Sprint across the room and back 10 times.",
  "Lie face down and lift both arms and legs off the floor for 1 minute (“Superman” hold).",
  "Push against a wall as hard as you can for 1 minute.",
  "Do 15 side lunges per side.",
  "Stand on tiptoe and hold for 2 minutes.",
  "Shadow box as fast as you can for 1 minute.",
  "Crawl under a table and back out 5 times.",
  "Hold the plank with one leg raised for 1 minute per leg.",
  "Do 20 knee-to-chest jumps.",
  "Sit cross-legged and get up without using your hands 10 times.",
  "200 burpees without stopping (break only if you puke).",
  "300 squats with arms locked overhead.",
  "Hold plank for 5 minutes straight—if you drop, restart the timer.",
  "150 push-ups in one go.",
  "Wall sit for 10 minutes (no shifting).",
  "200 mountain climbers × 3 sets.",
  "50 jump squats every minute for 10 minutes.",
  "10 minutes skipping rope non-stop—mess up = restart.",
  "Bear crawl across the room and back × 20.",
  "300 calf raises (on stairs).",
  "5 km run—under 30 minutes or redo tomorrow.",
  "1,000 jumping jacks in a single session.",
  "Crab walk across the room and back × 15.",
  "High knees for 3 minutes × 5 rounds.",
  "Push-up hold (halfway down) for 2 minutes × 3.",
  "Side plank 3 minutes per side × 3 sets.",
  "Walking lunges 200 steps without stopping.",
  "Sprint 100 m × 15 rounds.",
  "Burpee broad jumps across a field or big room.",
  "5-minute hollow body hold.",
  "300 Russian twists with a weight.",
  "10 minutes of stair sprints.",
  "2-minute squat hold × 5 rounds.",
  "250 push-ups with feet elevated.",
  "5 sets of 50 bicycles (core killer).",
  "Run 3 km backwards.",
  "200 kettlebell swings (or weighted object).",
  "Inch-worm walkouts × 50.",
  "Plank jacks for 10 minutes straight.",
  "Dead hang from a pull-up bar for 5 minutes (total time).",
  "Farmer’s carry heavy objects for 1 km.",
  "Side lunges × 200.",
  "Broad jumps × 100.",
  "Dive bomber push-ups × 150.",
  "Burpee to tuck jump × 100.",
  "Skater jumps × 500.",
  "20 rounds: 10 push-ups + 10 squats + 10 burpees.",
  "Sprint upstairs 30 times.",
  "100 surrenders (kneel to stand with weights).",
  "2-hour slow walk while carrying a loaded backpack."
];
