export const DARES_18_PLUS: string[] = [
  "Stand on a chair and sing like you’re auditioning for Indian Idol… but terribly.",
  "Shout “I just won the lottery” and run out of the room.",
  "Go to the window and confess fake love to a random passerby.",
  "Pretend to be a waiter and take “orders” from everyone in the group.",
  "Act like a news reporter describing the most boring object in the room.",
  "Pretend you’re possessed until someone “exorcises” you.",
  "Yell out a random Bollywood dialogue at full volume.",
  "Crawl on the floor like a baby until your turn ends.",
  "Call someone in your contacts and meow until they hang up.",
  "Introduce yourself to everyone again like you’re meeting them for the first time.",
  "Take 3 shots back-to-back without making a face.",
  "Chug your drink while maintaining eye contact with someone.",
  "Let the group create your next drink (no poison, but questionable mix).",
  "Pour a bit of every player’s drink into one cup and drink it.",
  "Take a shot without using your hands.",
  "Take a shot and then run around the room 5 times.",
  "Drink from someone else’s shoe (clean, hopefully).",
  "Swap drinks with the person on your left for the next 10 minutes.",
  "Drink while doing 10 squats.",
  "Drink while someone tells you the most depressing story they can.",
  "Post a random embarrassing selfie on Instagram stories without context.",
  "DM your crush: “Do you like bread?” and nothing else.",
  "Text your mom “I’m in trouble” and don’t reply for 10 minutes.",
  "Post “I just got engaged” on Facebook.",
  "Change your WhatsApp DP to a potato.",
  "Put “Open for adoption” in your bio for 24 hours.",
  "Post a video of you crying over something stupid (like an empty glass).",
  "Comment “Marry me” on your crush’s latest post.",
  "Change your name in the group chat to “The Chosen One.”",
  "Reply “Yes” to the last text you got from anyone.",
  "Do a handstand for as long as possible.",
  "Hold a plank until your next turn.",
  "Let two people draw on your arms with markers.",
  "Do 10 push-ups with someone sitting on your back.",
  "Eat something without using your hands.",
  "Try to juggle three random items.",
  "Balance a spoon on your nose for 30 seconds.",
  "Do a wall sit while singing.",
  "Spin in circles for 20 seconds and then walk straight.",
  "Run outside barefoot and touch the first tree you see.",
  "Whisper something dirty in the ear of the person to your right.",
  "Let someone write a word of their choice on your neck.",
  "Give a lap dance to someone (no excuses).",
  "Pretend to propose to the person across from you.",
  "Hold hands with someone for the next 5 minutes.",
  "Sit on someone’s lap until your turn comes again.",
  "Kiss someone’s cheek blindfolded.",
  "Give someone a shoulder massage.",
  "Blow a kiss to everyone in the group dramatically.",
  "Call someone “baby” until the round ends.",
  "Spin a bottle, whoever it lands on gives a 30-second lap dance to the person on their right. No music? Humming counts.",
  "Everyone kisses the person next to them on the lips, passing a piece of ice around the circle without using hands.",
  "Line up three people. First person does a shot from the second person’s navel, second person from the third’s.",
  "Players must auction their underwear to the group using only seductive talk. Winner pays with dares.",
  "Draw random roles from a hat (e.g., “horny pirate,” “strict teacher,” “flirty alien”). Act out a 2-minute scene with your partner while the group chooses the situation.",
  "Blindfold a player. Other players touch them with anything (keep it legal) and they have to guess what it is… using only lips or tongue.",
  "Refusing a truth/dare means removing one item of clothing.",
  "Each player must give their most convincing bedroom moan. Loser (judged by group) does a dare chosen by everyone else.",
  "Player must crawl across the floor, between everyone’s legs, and kiss the last person on the cheek, lips… or wherever they dare.",
  "One person does a dare, then tags the next. You must make it wilder than the previous one, or remove a clothing item.",
  "Let the group post any picture from your gallery as your story. No filters, no mercy.",
  "Call Your Crush: Put the phone on speaker, say “I dreamt about you last night” and hang up.",
  "Fill a bucket with freezing water and pour it over your head… in your underwear.",
  "Go outside and dramatically propose to a stranger with a shoe as a ring.",
  "Everyone in the group gets to ask you one question. You must answer honestly, no skipping.",
  "Full 1 minute, random dance moves, no music.",
  "Close your eyes, and let one random person slap you (lightly… or not).",
  "Mimic another player for the rest of the game—voice, mannerisms, everything.",
  "Eat a weird combo the group makes (pickle + chocolate + milk, anyone?).",
  "Pick the cringiest Bollywood song possible and perform like you’re in a music video.",
  "Go live for 1 minute and let the group decide what you do on camera.",
  "Give your phone to the group for 2 minutes. No unlocking conditions.",
  "One person dares you, you dare the next person, chain continues until someone refuses.",
  "Swap one clothing item with the person sitting opposite you.",
  "Go to your balcony/window and yell, “I’m sexy and I know it!” three times."
];
